staging: media/cec: Fix build after commit efcfcae33578
Apply changes done by commit "rc-main: assign driver type during allocation"
here as well to fix the following build error:

  /mnt/ssd/kernels/grus/drivers/staging/media/cec/cec-core.c:247:32: error: too few arguments to function call, expected 1, have 0
          adap->rc = rc_allocate_device();
                     ~~~~~~~~~~~~~~~~~~ ^
  /mnt/ssd/kernels/grus/include/media/rc-core.h:209:16: note: 'rc_allocate_device' declared here
  struct rc_dev *rc_allocate_device(enum rc_driver_type);
                 ^

Signed-off-by: Albert I <kras@raphielgang.org>